### ISSUE TITLE
Add a folder called Wolfram/Mathematica in Projects section

### ISSUE THREAD

**Issue by amandewatnitrr** [AkashSingh3031/The-Complete-FAANG-Preparation#113]
Mathematica/Wolfram is a very underrated programming Language. But from project point of view amazing projects can be created on Machine Learning, AI, Data Visaliztion, Data Analysis and Web Development.

Potential projects: https://demonstrations.wolfram.com/topics.php?MathematicaFunctionality

Please check the computation section here particularly. So, it's really not much explored but really high potential.

**Comment by AkashSingh3031** [comment]
Add this link to important resources file 📁
