### ISSUE TITLE
Create a pull request template to complete all the recommended community standards. 

### ISSUE THREAD

**Issue by Ranjul-Arumadi** [AkashSingh3031/The-Complete-FAANG-Preparation#135]
Create a [pull request template](https://blog.echobind.com/imagine-youve-recently-hired-a-new-engineer-to-join-your-team-224df7e5b967) to complete all the [recommended community standards](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/community). 

@AkashSingh3031, Considering the fact that the contributors are increasing, adding a PR template would be beneficial. 😊

**Comment by AkashSingh3031** [comment]
> Create a [pull request template](https://blog.echobind.com/imagine-youve-recently-hired-a-new-engineer-to-join-your-team-224df7e5b967) to complete all the [recommended community standards](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/community).
> 
> @AkashSingh3031, Considering the fact that the contributors are increasing, adding a PR template would be beneficial. 😊

@Ranjul-Arumadi 
Check this [pull request template ](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and tell me if any changes are required.
