### ISSUE TITLE
Textogram in web development

### ISSUE THREAD

**Issue by poojitha2002** [AkashSingh3031/The-Complete-FAANG-Preparation#150]
Can I contribute my project, Textogram in web dev projects? It is a web app which has options like converting text from lower case to upper case, calculates frequency of words, characters and words. Used formspree API and responsiveAPI for text to speech.

**Comment by AkashSingh3031** [comment]
Yes you can 
But, put your project on the proper path

**Comment by poojitha2002** [comment]
Thank you!
