### ISSUE TITLE
Regarding comment in code

### ISSUE THREAD

**Issue by harshil202** [AkashSingh3031/The-Complete-FAANG-Preparation#167]
Hi, I found that in the data structure folder all c++ code does not contain comments and I think a comment is also important for a new person to understand. If you want to add comments just let me know.

**Comment by AkashSingh3031** [comment]
> Hi, I found that in the data structure folder all c++ code does not contain comments and I think a comment is also important for a new person to understand. If you want to add comments just let me know.


Ok, you can add comments

**Comment by harshil202** [comment]
Ok, I will do that
