### ISSUE TITLE
Adding Kruskal’s Minimum Spanning Tree Algorithm and Dijkstra’s Shortest Path Algorithm in Python

### ISSUE THREAD

**Issue by mansijain980** [AkashSingh3031/The-Complete-FAANG-Preparation#170]
@AkashSingh3031 I want to add Algos for many tracks like Dynamic Programming, Greedy Algos, and some more algo of ML like Random Forest etc. in Python.

This issue is important for me. Please assign this to me asap. It's a request.

**Comment by AkashSingh3031** [comment]
> @AkashSingh3031 I want to add Algos for many tracks like Dynamic Programming, Greedy Algos, and some more algo of ML like Random Forest etc. in Python.
> 
> This issue is important for me. Please assign this to me asap. It's a request.
> 
> 

Ok, I assigned you
