### ISSUE TITLE
 Add LEARN.md

### ISSUE THREAD

**Issue by ericdrosado** [AkashSingh3031/The-Complete-FAANG-Preparation#263]
`Learn` repos should have a LEARN.md file to teach another student how to build a project repo. Your repo is a bit of an outlier in the sense that it doesn't follow our traditional `Learn` repo model. Could we move your index into a LEARN.md file so it declutters your README?

**Comment by AkashSingh3031** [comment]
Ok, Sir!

We add **` Table of Contents 📋`**, **` Tree of Index 🚀`**, and **`Domain 🔰`** in the `Learn.md` file.

**Comment by AkashSingh3031** [comment]
**[Learn.md](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/Learn.md)** file is ready

**Comment by ericdrosado** [comment]
The LEARN.md looks perfect! Closing this issue.
