### ISSUE TITLE
Reduce Topics

### ISSUE THREAD

**Issue by ericdrosado** [AkashSingh3031/The-Complete-FAANG-Preparation#264]
In Community Exchange, GitHub Topics will help the discoverability of your project. For repo types we will add `Learn` and `Collaborate` to your repo topics. This will help students sort by these repo types. You are currently at the max limit of topics. Would it be possible to remove two topics to accommodate the `Learn` and `Collaborate` topics we will add?

**Comment by AkashSingh3031** [comment]
We can merge `1]. DSA` and `3]. Competitive Programming` as `1]. DSA + CP`
under `DSA + CP` topic there are two folders, **1. DSA** & **2. Competitive Programming**

**Comment by ericdrosado** [comment]
@AkashSingh3031 when I refer to topics, I'm referring to these:  

![Screen Shot 2022-05-18 at 2 27 16 PM](https://user-images.githubusercontent.com/10368374/169140548-c35faccf-d9ee-43a0-bfec-fd5df106106a.png)

You can find more information about topics [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository)

**Comment by AkashSingh3031** [comment]
> @AkashSingh3031 when I refer to topics, I'm referring to these:
> 
> ![Screen Shot 2022-05-18 at 2 27 16 PM](https://user-images.githubusercontent.com/10368374/169140548-c35faccf-d9ee-43a0-bfec-fd5df106106a.png)
> 
> You can find more information about topics [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository)

Done

**Comment by ericdrosado** [comment]
I'm counting 19 topics. You will need to remove one more so we have 18 total.

**Comment by AkashSingh3031** [comment]
> I'm counting 19 topics. You will need to remove one more so we have 18 total.

![image](https://user-images.githubusercontent.com/60146338/169217121-5e0ab2d4-daf1-4aa7-a88d-579d736997dd.png)

**Comment by ericdrosado** [comment]
Perfect! Closing this issue. 🚀
