### ISSUE TITLE
Add issue(s)

### ISSUE THREAD

**Issue by ericdrosado** [AkashSingh3031/The-Complete-FAANG-Preparation#265]
As the maintainer of a `Collaborate` repo, keeping Issues up-to-date will help the student community understand what they can do to contribute.

Perhaps there are interview questions from a certain company you are interested in adding to your repo? I'd recommend generating an issue for that. 

In order to submit your project into CX you will need at least one open issue.

**Comment by AkashSingh3031** [comment]
@ericdrosado 
Added two issues for public

- [ ] #266
- [ ] #267

**Comment by ericdrosado** [comment]
@AkashSingh3031 I would recommend creating issues that are specific. The two issues you generated are broad, and might not be appropriate as an Issue. Issues should address a specific problem where someone can work on that problem and then close the issue. 

An example might be to create an issue seeking contributors to add `Quantitative Analysis` material to `Miscellaneous Stuff` since there is no content in that folder currently. This issue would be specific and a contributor could work on it and close that issue. 

Let me know if that makes sense or if you would like to brainstorm some ideas.

**Comment by AkashSingh3031** [comment]
> @AkashSingh3031 I would recommend creating issues that are specific. The two issues you generated are broad, and might not be appropriate as an Issue. Issues should address a specific problem where someone can work on that problem and then close the issue.
> 
> An example might be to create an issue seeking contributors to add `Quantitative Analysis` material to `Miscellaneous Stuff` since there is no content in that folder currently. This issue would be specific and a contributor could work on it and close that issue.
> 
> Let me know if that makes sense or if you would like to brainstorm some ideas.

Ok, I understand

**Comment by ericdrosado** [comment]
@AkashSingh3031 any updates on creating an issue?

**Comment by AkashSingh3031** [comment]
> @AkashSingh3031 any updates on creating an issue?

@ericdrosado
Added three issues for public

- [ ] #278 
- [ ] #279 
- [ ] #280 

it is fine?

**Comment by ericdrosado** [comment]
I would recommend instead of using `You are all welcome to contribute to` that you use `Looking for content related to`. 

What do you think?

**Comment by AkashSingh3031** [comment]
> I would recommend instead of using `You are all welcome to contribute to` that you use `Looking for content related to`.
> 
> What do you think?

Yes, this comment seems to be correct.
I updated the comment

**Comment by ericdrosado** [comment]
Perfect! Closing this issue 👍
