### ISSUE TITLE
TypeScript | JavaScript Data Structures

### ISSUE THREAD

**Issue by nisabmohd** [AkashSingh3031/The-Complete-FAANG-Preparation#342]
JavaScript is one of the popular programming languages used at Leetcode by many users. 
And TypeScript is a wrap up to JS and have very good Type support.
Hence there must be section of Data Structures in this language too.

**Comment by AkashSingh3031** [comment]
Some `JS Array DS` code has been already added
If you want to add `CP Code in JS` then you can create a `JavaScript` folder and add code in the folder
