### ISSUE TITLE
Unable to pull due to filename length

### ISSUE THREAD

**Issue by Silly26** [AkashSingh3031/The-Complete-FAANG-Preparation#345]
![image](https://user-images.githubusercontent.com/8854060/215825451-485fedae-18fd-43d1-8fba-b837697ce76b.png)

Windows users are unable to clone/pull these particular files.

**Comment by rashmiraj513** [comment]
Faced the same issue while cloning this repo.

**Comment by AkashSingh3031** [comment]
@Silly26, @rashmiraj513 
If you get this issue then you can run this in git
`git config --system core.longpaths true`

then try to send a pull request

Git has a limit of 4096 characters for a filename
and msys has a limit of 260 characters for a filename

You can check this [Add Windows long path support](https://github.com/msysgit/git/pull/110)
