### ISSUE TITLE
In projects Machine learning 

### ISSUE THREAD

**Issue by work-mohit** [AkashSingh3031/The-Complete-FAANG-Preparation#36]
Machine learning projects can be further categorized by 
1. Data Analysis Projects
2. ML Projects
3. Deep Leaning Projects

**Comment by AkashSingh3031** [comment]
> Machine learning projects can be further categorized by
> 
> 1. Data Analysis Projects
> 2. ML Projects
> 3. Deep Learning Projects

@work-mohit 
Ok, thanks for giving suggestion

**Comment by AkashSingh3031** [comment]
@work-mohit 
I created the folder but after add projects in the ML folder then got an issue
Can change `python` folder into [`2]. ML  Projects`](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/tree/master/5%5D.%20Projects/Machine%20Learning%20%26%20Data%20Science%20%20(ML-DS)) folder

**Comment by AkashSingh3031** [comment]
@work-mohit 
Can you add an empty `Add_Context.txt` file in empty folders and send a pull request

Because another folder not visible

**Comment by AkashSingh3031** [comment]
@work-mohit 
Category folder like

- Data AnalysisProject
   - `Add_context.txt`
- Deep Learning
   - `Add_context.txt`
- Machine Learning 
   - `Add_context.txt`
- Natural Language Processing
   - `Add_context.txt`
- Computer Vision
   - Python
      -  `put all 8 projects`

**Comment by work-mohit** [comment]
Ok will do !

**Comment by AkashSingh3031** [comment]
@work-mohit  can you tell me how to pull the large file into the system
Because, when pulling the file then got an error  ` Filename too long`

**Comment by work-mohit** [comment]
https://stackoverflow.com/questions/52699177/how-to-fix-filename-too-long-error-during-git-clone/52699496

https://www.javaprogramto.com/2020/04/git-filename-too-long.html#:~:text=If%20you%20have%20clone%20already,git%22%20folder 

You can follow this two links

**Comment by AkashSingh3031** [comment]
@work-mohit  
Thanks, it's working
Now  pull & commit complete

**Comment by work-mohit** [comment]
Happy to help brother!
