### ISSUE TITLE
Error in the Hacktoberfest tag 

### ISSUE THREAD

**Issue by juanpflores** [AkashSingh3031/The-Complete-FAANG-Preparation#375]
### Have you read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md)?

**Describe the bug**
The Hacktoberfest tag on the repository is not written correctly which will make the contributions invalid for the event. 

**To Reproduce**
NA

**Expected behavior**
The tag should be `hacktoberfest`

**Screenshots**
![Screenshot 2023-10-03 120012](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/assets/6200135/bfd9a27b-c829-4816-8761-68c10879fc8b)

**Additional context**
- Add any other context about the problem here.

**Comment by AkashSingh3031** [comment]
@juanpflores Thanks for raised this issue

Now resolved this mistake
