### ISSUE TITLE
Welcome to The-Complete-FAANG-Preparation Discussions!

### ISSUE THREAD

**Issue by AkashSingh3031** [AkashSingh3031/The-Complete-FAANG-Preparation#43]
### Discussed in https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **AkashSingh3031** June 16, 2021</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by Anson115413** [comment]
If you force to open the file you will be liable for any damages

**Comment by Anson115413** [comment]
You already open it ! But not the full node core! The project is intentionally hide to the public.

**Comment by AkashSingh3031** [comment]
> You already open it ! But not the full node core! The project is intentionally hide to the public.

Can you explain to me in detail what you want to say?

**Comment by Anson115413** [comment]
Iam the developer of the project I already block your account

**Comment by Anson115413** [comment]
Your not allowed to share the code
