### ISSUE TITLE
What mobile projects we are planning develop?

### ISSUE THREAD

**Issue by arjadhav11codes** [AkashSingh3031/The-Complete-FAANG-Preparation#47]
I mean here, is there any requirements or design spec to start working on the mobile projects.
I want to contribute for Android platform.

**Comment by AkashSingh3031** [comment]
@arjadhav11codes 
You can contribute your project
Create a folder with a number like `01)_<your project name>` then put your project in that folder
if possible try to show preview in `.md` file
