### ISSUE TITLE
Contribution Open for All

### ISSUE THREAD

**Issue by thecoder8890** [AkashSingh3031/The-Complete-FAANG-Preparation#9]

**Comment by AkashSingh3031** [comment]
@thecoder8890 
𝐓𝐡𝐢𝐬 𝐢𝐬 𝐚𝐧 𝐨𝐩𝐞𝐧 𝐬𝐨𝐮𝐫𝐜𝐞 𝐩𝐫𝐨𝐣𝐞𝐜𝐭, 𝐜𝐨𝐧𝐭𝐫𝐢𝐛𝐮𝐭𝐢𝐨𝐧 𝐨𝐩𝐞𝐧 𝐟𝐨𝐫 𝐚𝐥𝐥
Feel free to contribute your work to this repository. 

This is Tree of Index where you contribute your work and learn from other resources too 
.
├── ...
├── 𝑴𝒊𝒔𝒄𝒆𝒍𝒍𝒂𝒏𝒆𝒐𝒖𝒔 𝑺𝒕𝒖𝒇𝒇
 |        └── ...
 |
└── 𝑫𝑺𝑨
 |          ├── Data Structures
 |           |       └── ...
 |          ├── Algorithms
 |           |        └── ...
 |          ├── 450 DSA by @Love Babbar
 |           |       └── ...
 |          ├── FAANG Interview Questions
 |           |       └── ...
 |          └── ...
 |
└── 𝑪𝒐𝒎𝒑𝒆𝒕𝒊𝒕𝒊𝒗𝒆 𝑷𝒓𝒐𝒈𝒓𝒂𝒎𝒎𝒊𝒏𝒈
 |          └── ...
 |
└── 𝑻𝒆𝒄𝒉𝒏𝒊𝒄𝒂𝒍 𝑺𝒖𝒃𝒋𝒆𝒄𝒕
 |        ├── Object Oriented Programming (OOPs)
 |         |       └── ...
 |        ├── Operating System (OS)
 |         |        └── ...
 |        ├── Database Management System (DBMS)
 |         |       └── ...
 |        ├── Structured Query Language (SQL)
 |         |       └── ...
 |        ├── Computer Network (CN)
 |         |       └── ...
 |        ├── Interview Questions
 |         |       └── ...
 |        └── ...
 |
└── 𝑳𝒐𝒘 𝑳𝒆𝒗𝒆𝒍 𝑫𝒆𝒔𝒊𝒈𝒏
│       └── ...
 |
└── 𝑷𝒓𝒐𝒋𝒆𝒄𝒕
 |        ├── Machine Learning & Data Science
 |         |       └── ...
 |        ├── Internet of Things (IoT)
 |         |       └── ...
 |        ├── Web Development
 |         |       └── ...
 |        ├── Mobile Development
 |         |       └── ...
 |        └── ...
└── ...

**Comment by thecoder8890** [comment]
Ok sure will provide the input

**Comment by thecoder8890** [comment]
@AkashSingh3031 : Raised a PR for Hackerrank Solution : - https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/pull/12

**Comment by thecoder8890** [comment]
@AkashSingh3031 : Leetcode solutions https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/pull/16, Please check and merge

**Comment by AkashSingh3031** [comment]
@thecoder8890 
Already have a Folder `Problems` and add solution code in a folder
like  `_0002)_Add_Two_Numbers.java`  instead of  `Java/Easy/AddTwoNumbers.java `

**Comment by ghana7989** [comment]
It is unclear how to contribute.
Can @AkashSingh3031 give a detailed example or how to contribute to THIS project.
I find many empty text files. Instead I expect it should be mentioned what is required there. 
Once I understand how to contribute. I am ready to contribute.

**Comment by AkashSingh3031** [comment]
> @thecoder8890
> 𝐓𝐡𝐢𝐬 𝐢𝐬 𝐚𝐧 𝐨𝐩𝐞𝐧 𝐬𝐨𝐮𝐫𝐜𝐞 𝐩𝐫𝐨𝐣𝐞𝐜𝐭, 𝐜𝐨𝐧𝐭𝐫𝐢𝐛𝐮𝐭𝐢𝐨𝐧 𝐨𝐩𝐞𝐧 𝐟𝐨𝐫 𝐚𝐥𝐥
> Feel free to contribute your work to this repository.
> 
> This is Tree of Index where you contribute your work and learn from other resources too
> 
> ```js
> .
> ├── ...
> ├── 𝑴𝒊𝒔𝒄𝒆𝒍𝒍𝒂𝒏𝒆𝒐𝒖𝒔 𝑺𝒕𝒖𝒇𝒇
> |   ├── Aptitude & Reasoning              
> |   |   └── ...
> |   |
> |   ├── Basic Programming MCQs
> |   |   └── ...
> |   |
> |   ├── Puzzles
> |   |   └── ...
> |   |
> |   └── ...
> |
> |
> └── 𝑫𝑺𝑨
> |   ├── Data Structures              
> |   |   └── ...
> |   |
> |   ├── Algorithms
> |   |   └── ...
> |   |
> |   ├── 450 DSA by @Love Babbar
> |   |   └── ...
> |   |
> |   ├── FAANG Interview Questions
> |   |   ├── Facebook
> |   |   ├── Amazon
> |   |   ├── Apple
> |   |   ├── Netflix
> |   |   ├── Google
> |   |   ├── Others
> |   |   └── ...
> |   |
> |   └── ...
> |
> |
> └── 𝑪𝒐𝒎𝒑𝒆𝒕𝒊𝒕𝒊𝒗𝒆 𝑷𝒓𝒐𝒈𝒓𝒂𝒎𝒎𝒊𝒏𝒈
> |   ├── HackerRank              
> |   |   └── ...
> |   |
> |   ├── GeeksforGeeks
> |   |   └── ...
> |   |
> |   ├── HackerEarth
> |   |   └── ...
> |   |
> |   ├── CodeChef              
> |   |   └── ...
> |   |
> |   ├── CodeForce
> |   |   └── ...
> |   |
> |   ├── LeetCode
> |   |   └── ...
> |   |
> |   ├── InterviewBit
> |   |   └── ...
> |   |
> |   └── ...
> |
> |
> └── 𝑻𝒆𝒄𝒉𝒏𝒊𝒄𝒂𝒍 𝑺𝒖𝒃𝒋𝒆𝒄𝒕
> |   ├── Object Oriented Programming (OOPs)              
> |   |   └── ...
> |   |
> |   ├── Operating System (OS)
> |   |   └── ...
> |   |
> |   ├── Database Management System (DBMS)
> |   |   └── ...
> |   |
> |   ├── Structured Query Language (SQL)              
> |   |   └── ...
> |   |
> |   ├── Computer Network (CN)
> |   |   └── ...
> |   |
> |   ├── Interview Questions
> |   |   └── ...
> |   |
> |   └── ...
> |
> |
> └── 𝑳𝒐𝒘 𝑳𝒆𝒗𝒆𝒍 𝑫𝒆𝒔𝒊𝒈𝒏   
> │   └── ...
> |
> |
> └── 𝑷𝒓𝒐𝒋𝒆𝒄𝒕
> |   ├── Machine Learning & Data Science              
> |   |   └── ...
> |   |
> |   ├── Internet of Things (IoT)
> |   |   └── ...
> |   |
> |   ├── Web Development
> |   |   └── ...
> |   |
> |   ├── Mobile Development              
> |   |   └── ...
> |   |
> |   └── ...
> └── ...
> ```




@ghana7989 
This is `Tree of Index` 
You can contribute your interested Topic see above

**Comment by thecoder8890** [comment]
@AkashSingh3031  : I have created the https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/pull/34 for **Top 50 DBMS interview questions**

**Comment by farheen21** [comment]
@AkashSingh3031 hey I am also willing to contribute in Dsa by love babber as I am doing this sheet so wanna ask how should I send the PR like just question number and code or have provide approaches in readme file as well?

**Comment by AkashSingh3031** [comment]
> @AkashSingh3031 hey I am also willing to contribute in Dsa by love babber as I am doing this sheet so wanna ask how should I send the PR like just question number and code or have provide approaches in readme file as well?

@farheen21 
Only send the running & Accepted Code on IDE
And Save the file in the folder with a number like `_01)_<problem name>`
You can explain code in the editor with comments, 

if possible update the [`Readme.md`](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/tree/master/1%5D.%20DSA/450%20DSA%20by%20(%20Love%20Babbar%20Bhaiya%20)#450-dsa-sheet) file with your solution link.

**Comment by farheen21** [comment]
> > @AkashSingh3031 hey I am also willing to contribute in Dsa by love babber as I am doing this sheet so wanna ask how should I send the PR like just question number and code or have provide approaches in readme file as well?
> 
> @farheen21
> Only send the running & Accepted Code on IDE
> And Save the file in the folder with a number like `_01)_<problem name>`
> You can explain code in the editor with comments,
> 
> if possible update the [`Readme.md`](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/tree/master/1%5D.%20DSA/450%20DSA%20by%20(%20Love%20Babbar%20Bhaiya%20)#450-dsa-sheet) file with your solution link.

okay got it soon I will send PR for respective subject...

**Comment by amandewatnitrr** [comment]
I would like to contribute to this project please let me know how can i contribute

**Comment by AkashSingh3031** [comment]
> I would like to contribute to this project please let me know how can i contribute

Follow [`Tree of Index`](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index)

**Comment by AkashSingh3031** [comment]
> > I would like to contribute to this project please let me know how can i contribute
> 
> Follow [`Tree of Index`](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index)

You can contribute your interested area
